### ISSUE TITLE
Failed loading user32: user32: cannot open shared object file: No such file or directory (RuntimeError)

### ISSUE THREAD

**Issue by JeremyRand** [mkxp-z/mkxp-z#1]
I built mkxp-z (c41967268c7ad62b3eb62938d9ca644ddabff3e6) from source for Debian Bullseye ppc64le.  It built without issues, but when running any game, I get this error:

~~~
$ ./mkxp-z.ppc64le 
RGSS version 3 (RPG Maker VX Ace) 
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
ALC_SOFT_pause_device present 
Backend      : OpenGL 
GL Vendor    : Mesa/X.org 
GL Renderer  : llvmpipe (LLVM 11.0.1, 128 bits) 
GL Version   : 3.1 Mesa 20.3.5 
GLSL Version : 1.40 
124::642:in `initialize': Failed loading user32: user32: cannot open shared object file: No such file or directory (RuntimeError)
        from 124::642:in `new'
        from 124::642:in `singleton class'
        from 124::639:in `<main>' 
EventThread termination requested 
RGSS thread ack'd request after 0 ms 
Shutting down.
~~~

I get a similar error in Falcon-mkxp when I don't specify a Windows wrapper script, so I assume I need one here too, but I can't find the `my_win32_wrapper.rb` script that's referenced in the `mkxp.json` example.

**Comment by JeremyRand** [comment]
As an aside I'm really impressed that the build system handled ppc64le without any issues; kudos on that.

**Comment by ghost** [comment]
The game is trying to load a Windows library somewhere; you gotta go in and reprogram it not to do that. mkxp-z implements Win32API, but it's all native, so it can't load things that the OS can't

Any wrapper script probably attempted to fake Win32API, but the regular old mkxp never included a script like that on its own (that I know of), so I don't have one either -- the assumption generally being that anyone using this probably wants to *make* the game, or knows enough to patch up any broken bits on their own, so trying to emulate Win32API didn't make much sense when I could just skip that part and extend mkxp myself

> As an aside I'm really impressed that the build system handled ppc64le without any issues;

Surprise to me, but it's probably just because I also had to make sure it worked on arm64

**Comment by JeremyRand** [comment]
OK, that makes sense.  It was not clear to me from the documentation that the Win32API support was Windows-only, but yeah, now that I look at the source code, it's obvious that what I was trying to do wouldn't be expected to work.  Any chance the documentation could be clarified to indicate that Win32API support will only work on Windows?

**Comment by ghost** [comment]
That's the thing -- the class itself is there, it's the libraries that aren't. If someone wanted to use a library that they wrote themselves or is naturally shipped across multiple platforms, you could use it for that. It's the main reason it's there actually, even if no one will ever use it for that but potentially me.

I do try to make it known:

> + It runs on Linux and macOS. This doesn't mean you can run Windows libraries on those platforms. It *does* mean that you can use libraries built for each respective platform (shared objects with linux, .dylibs and frameworks on macOS).

Everybody seems to miss that part though.

**Comment by JeremyRand** [comment]
Yeah, so I did actually read that part, but I misinterpreted "Windows libraries" to mean ".dll files provided by the user" rather than "the standard .dll files that Windows ships with to implement the Windows API".  I think it could be made less confusing just by inserting a parenthetical "(e.g. the .dll files that Windows ships with to implement the standard Windows API)" after "Windows libraries".  I get that the current docs are technically accurate, it's just not super accessible to people who aren't familiar with how the codebase works.

**Comment by ghost** [comment]
Maybe. I always figured that should just be enough, but it could be reworded. I'll probably do that

**Comment by ghost** [comment]
Done, should be a little clearer now, I hope

**Comment by JeremyRand** [comment]
Thanks, the new wording LGTM.
