### ISSUE TITLE
[Request] Use LTO flag to further improve performance

### ISSUE THREAD

**Issue by Nathan-MV** [mkxp-z/mkxp-z#16]
Major linux distributions are using it in all their packages aka (Ubuntu, Fedora, OpenSUSE...)
-O3 reduced a lot the time we spent compiling the PBS, would be nice to see if -flto=full (and maybe -march=x86-64-v3) can reduce further.

**Comment by ghost** [comment]
I think this is more of a benefit to ruby than mkxp itself, so I may build Ruby specifically with it turned on
I don't think what it does to compile time is worth it for the rest (last time I tried, I don't think it reduced the file size either, which is what I was looking at it for)

**Comment by Nathan-MV** [comment]
The -O3 flag reduced in 4x the time spent compiling PBS.

**Comment by ghost** [comment]
Essentials PBS files are handled by Ruby, as most things are, no? The vast majority of performance bottlenecks are probably gonna be within Ruby, which is just slow by nature

If I built Ruby statically within mkxp-z I'd probably need to apply LTO to mkxp-z, too, but ruby is kept separate, so you should still get what you want, I think
