### ISSUE TITLE
Input::getButtonName() sees some defined names as "Invalid"

### ISSUE THREAD

**Issue by Eblo** [mkxp-z/mkxp-z#172]
In `input.cpp`, the `buttonNames` variable currently defines 21 name values for game pad buttons. However, `getButton()` has a check to see if the provided number is greater than or equal to `SDL_CONTROLLER_BUTTON_MAX`, which is 15 as of this issue. This means that the the last several defined values in `buttonNames` serve no purpose.

I don't know if the solution is to change that conditional or to remove those values. I'm leaning towards the latter. I imagine that, if SDL itself does not understand those values, they won't do anything anyway.

**Comment by Splendide-Imaginarius** [comment]
Very weird. Who wrote the affected code? Struma? If it's someone who is still reachable, it'd be nice to ask them what the intent was.

**Comment by WaywardHeart** [comment]
@Eblo You're looking at either the wrong branch or an outdated fork. mkxp-z is currently using the mkxp-z-2.28.1 branch of our SDL fork, which does define 21 buttons.

**Comment by Eblo** [comment]
You're right. I had made an SDL fork to sidestep an ANGLE bug I had, but that was before mkxp-z bumped its SDL version. My bad.
