### ISSUE TITLE
too many parameters

### ISSUE THREAD

**Issue by Splendide-Imaginarius** [mkxp-z/mkxp-z#2]
I have a game that shows the error `RuntimeError occurred. too many parameters: 12/10` when launched with mkxp-z on Windows. I suspect this is related to the MiniFFI module being limited to 10 arguments. If that is indeed the source of the issue, would a PR be accepted that bumps the limit from 10 to 12? It looks like the reason for the limit of 10 is the assumption "You'll probably never even make it to 10." Unfortunately it looks like that assumption was wrong, at least for the first game I tested.

**Comment by Splendide-Imaginarius** [comment]
PR incoming shortly.

**Comment by Splendide-Imaginarius** [comment]
> Unfortunately it looks like that assumption was wrong, at least for the first game I tested.

And the second game I tested too. (Also needs 12 parameters.)

**Comment by ghost** [comment]
When I wrote it, given Essentials was/is generally the benchmark, it definitely seemed the case. If it bugs you, may as well bump it to 16, which is how many it would normally take. What APIs are these that need so many parameters?

**Comment by Splendide-Imaginarius** [comment]
> When I wrote it, given Essentials was/is generally the benchmark, it definitely seemed the case. If it bugs you, may as well bump it to 16, which is how many it would normally take.

OK, I can update my PR to bump to 16 instead. Might take me a few days.

> What APIs are these that need so many parameters?

I'm not actually sure; the existing error message doesn't say which API function is being called, and I never bothered to add more details to that error message since it seemed easier to just fix it. If you're curious (and I admit I'm curious too), I can look into it.

**Comment by Splendide-Imaginarius** [comment]
> > What APIs are these that need so many parameters?
> 
> I'm not actually sure; the existing error message doesn't say which API function is being called, and I never bothered to add more details to that error message since it seemed easier to just fix it. If you're curious (and I admit I'm curious too), I can look into it.

Looks like the 12-arg API function (in one of the affected games I tested, didn't check the other one) is `user32:CreateWindowEx`. I'm not sure what the game is using this function for, but on non-Windows platforms I just ignore that Windows function via a preload script, and the game doesn't show any obviously-bad behavior.

**Comment by ghost** [comment]
Nutty. Anyway, sure, I'll look at the pull requests this weekend, so take your time.

**Comment by Splendide-Imaginarius** [comment]
PR has been bumped to 16 args (though I don't know of any games that use 13 or more, so the testing I could do was limited). I'm not in a huge hurry to get my PR's merged (none of these are actively blocking further development on my end), so the weekend is certainly fine.

**Comment by Splendide-Imaginarius** [comment]
Sent in a few more PR's. If the volume of PR's from me is overwhelming you, please let me know and I can throttle my output a bit. On the other hand, if you want to power through as many of them as possible over the weekend, now you can batch a few more in.

**Comment by ghost** [comment]
Nah, not overwhelmed per se, I'm just slow

I'll have a look at them all once I'm not busy or whatever passes for busy. Meantime though, I merged that PR, so I'll close this particular issue.
