### ISSUE TITLE
MacOS 'Graphics.transition' image load error

### ISSUE THREAD

**Issue by lunarcloud** [mkxp-z/mkxp-z#25]
The message:
"Script 'Scene_Map' line 255:
SDLError occured.

Error loading image 'Graphics/Systems/BattleStart': Unknown pixel format"

<img width="210" alt="image" src="https://github.com/mkxp-z/mkxp-z/assets/1565970/962cb9b9-6d59-46b0-b4ff-622112b8970c">

Didn't make a difference whether using Metal or openGL (tested on M1 macbook)

Code from that script (line 255 is the transition itself):
```rb
  #--------------------------------------------------------------------------
  # * Execute Pre-Battle Transition
  #--------------------------------------------------------------------------
  def perform_battle_transition
    Graphics.transition(60, "Graphics/System/BattleStart", 100)
    Graphics.freeze
  end
```

P.S.
Was trying to upgrade this old game from the classic MKXP to this MKXP-Z - it's worked very well for the Linux version.

**Comment by ghost** [comment]
Which format is it in? the build process by default uses a newer version of SDL_image than Windows or Linux does at the moment

**Comment by Splendide-Imaginarius** [comment]
Does https://github.com/mkxp-z/mkxp-z/pull/24 affect the behavior at all (perhaps causing the same bug to show up on Linux and Windows)? (That PR upgrades the SDL_image dependency.)

**Comment by Splendide-Imaginarius** [comment]
Per nathanmv9480 on Matrix:

> It seems that the new build with the updated SDL2 is giving `Unknown pixel format` in XP transitions

The new build he's referring to bumped SDL_image on both Windows and Linux. So yes it seems likely that the SDL_image upgrade might have something to do with this. It also bumped SDL itself but that seems less likely to be the culprit.

**Comment by Splendide-Imaginarius** [comment]
I think this is due to https://github.com/libsdl-org/SDL_image/issues/294 . I'll look into bumping the SDL_image dependency to pull in the fix.

**Comment by Splendide-Imaginarius** [comment]
I've just bumped mkxp-z's fork of SDL_image to v2.6.3, which I think should pull in the fix for this bug.

@lunarcloud @ijuintekka could you see if it's fixed for you now? (You'll need to rebuild the deps from scratch.)

**Comment by ijuintekka** [comment]
It's fixed for me.

**Comment by Splendide-Imaginarius** [comment]
Excellent. Closing as fixed, then. @lunarcloud please let me know if you need the issue re-opened.
