### ISSUE TITLE
Use Ancurio's Ruby v1.8 preload wrapper

### ISSUE THREAD

**Issue by Splendide-Imaginarius** [mkxp-z/mkxp-z#40]
When I added https://github.com/mkxp-z/mkxp-z/blob/dev/scripts/preload/ruby18_wrap.rb in #6, I was unaware that @Ancurio had already implemented the exact same (character for character) function in 2014, but with an extra function that apparently helps some games. Their version is at https://pastebin.com/w5xx0N2N (CC0 license per Matrix/Discord conversation). Probably we should nuke my version in favor of theirs.

**Comment by WaywardHeart** [comment]
If you're going to be adding stuff to it, here's a more thorough script that also fixes some VX Ace games.

<details>
  <summary>ruby_classic_wrap.rb</summary>

```
class Hash
	alias_method :index, :key unless method_defined?(:index)
end

class Object
	TRUE = true unless const_defined?("TRUE")
	FALSE = false unless const_defined?("FALSE")
	NIL = nil unless const_defined?("NIL")
	
	alias_method :id, :object_id unless method_defined?(:id)
	alias_method :type, :class unless method_defined?(:type)
end

class NilClass
	def id
		4 # Starting with Ruby2, 64-bit builds of ruby make this 8
	end
end

class TrueClass
	def id
		2 # Starting with Ruby2, 64-bit builds of ruby make this 20
	end
end

if defined?(BasicObject) && BasicObject.instance_method(:initialize).arity == 0
	# In ruby 1.9.2, and only ruby 1.9.2, BasicObject.initialize accepted any number of arguments
	class BasicObject
		def initialize(*args)
		end
	end
end
```

</details>

**Comment by Splendide-Imaginarius** [comment]
@WaywardHeart nice, what's the license on that one? Is it yours?

**Comment by WaywardHeart** [comment]
Yeah, I put it together. It's CC0.

**Comment by Splendide-Imaginarius** [comment]
@WaywardHeart Great, would you be able to submit a PR that replaces the current script with yours?
