### ISSUE TITLE
Remove fps limit

### ISSUE THREAD

**Issue by Nathan-MV** [mkxp-z/mkxp-z#64]
![image](https://github.com/mkxp-z/mkxp-z/assets/67521199/baabe64b-80bf-407a-8373-50083cbe5abb)

**Comment by Eblo** [comment]
First thing regarding this example code, it isn't quite correct. `value` gets ignored, meaning the framerate will *always* be the maximum value of int (good luck running a game anywhere near that!). It should be something more like: `p->frameRate = clamp(value, 10, std::numeric_limits<int>::max());`

I don't think this would cause any unexpected issues from the mkxp-z side. All this does is remove a cap that mirrors the RGSS2/3 standard. It's comparable to how mkxp already removes the built-in resolution limitation of 640x480. It will not affect games that don't try to exceed this limit to begin with. Games that would even want to go near or past 120 FPS are likely doing something specialized anyway.
![image](https://github.com/mkxp-z/mkxp-z/assets/7004497/49715bfb-3cb4-4317-ac8b-68235851c569)

I've actually messed with the minimum value myself. I had to set it to 1, as the minimum of 10 was actually higher than the frame rate of a video I tried to play. I think some other code changes came later that made this fix irrelevant. See: https://github.com/Eblo/mkxp-z-eulogy/commit/993e9ea052dabd76c6b1b5144a58452f52c59335

**Comment by Splendide-Imaginarius** [comment]
Why is there a minimum framerate? I can totally believe that most devs don't have a use for going below 10 FPS, but does it harm anything to let them run at 1 FPS if they really want to?

**Comment by Eblo** [comment]
The reason why mkxp does that is most likely to match the spec shown above. The reason why RPG Maker does it "who knows". As long as the FPS is above 0, there shouldn't be any issues. The upper bound might as well be removed entirely.

**Comment by Splendide-Imaginarius** [comment]
> The reason why mkxp does that is most likely to match the spec shown above. The reason why RPG Maker does it "who knows". As long as the FPS is above 0, there shouldn't be any issues. The upper bound might as well be removed entirely.

@Eblo In that case I think I'd be in favor of removing the clamp altogether, though we'd still need a sanity check to make sure the number is positive.

**Comment by Nathan-MV** [comment]
If people wanted limits they would be using stock
