### ISSUE TITLE
Encryption with .zip

### ISSUE THREAD

**Issue by Nathan-MV** [mkxp-z/mkxp-z#79]
Encrypted .zip are better than RGSSAD (there's just too many RGSSAD Decryptor on the wild)

**Comment by Nathan-MV** [comment]
@Eblo i remember seeing some kind of new encryption in your fork, if you can give some details about it

**Comment by Splendide-Imaginarius** [comment]
The kind of encryption Enterbrain markets is snake oil, and if the laws in Japan were competently designed, they would have been sued for fraud for including that feature. I don't have any interest in adding snake oil to mkxp-z. The only reason mkxp-z supports encryption is to expose the snake oil that Enterbrain added for what it is, not to facilitate Enterbrain's fraud.

**Comment by Nathan-MV** [comment]
Just to clarify, i don't really care about encryption, but there are commercial games being developed by some people that use mkxp, so it would probably be interesting to have a decent encryption that mkxp is compatible with, because RGSSAD is total garbage

**Comment by Splendide-Imaginarius** [comment]
There is no such thing as decent encryption that does what Enterbrain tries to do. The laws of math are not compatible with such a thing. Just because Enterbrain defrauded a bunch of developers into thinking their encryption was good doesn't mean I'm going to do that.

**Comment by Nathan-MV** [comment]
Translation of RGModern encryption

RGModern supports encryption of image material.

First you need to create an encrypted package. Use 7-zip software to package the Graphics folder into a zip file and set a password. Note that the zip file should contain the Graphics directory.

This will be called before the game starts loading the graphics:

Finder.regist("Graphics.zip", "password")
where the first parameter is the filename of the encrypted package and the second parameter is the password of the encrypted package. After that it will prioritize reading the image material from the encrypted package, if there is no corresponding material in the encrypted package, it will look for it from the game directory and RTP.

RGModern does not support encrypted music clips.

RGModern supports encrypting Data folder. If you use RGM Assistant to compile, you can select the corresponding Data folder. If you don't use RGM Assistant, please refer to Gamew.exe in Makefile.

RGModern does not support the original encryption scheme. As we all know, the original encryption scheme is the same as no encryption, and RGModern will not support the original encryption scheme in the future.

**Comment by Splendide-Imaginarius** [comment]
Pasting documentation from some other snake oil product is not going to change the laws of math, sorry.

**Comment by Eblo** [comment]
> @Eblo i remember seeing some kind of new encryption in your fork, if you can give some details about it

That was from forever ago, ported from something I tried to do in a DLL to concoct something that would at least serve as better protection than `0xDEADCAFE` that 20 or so decrypters on the front page of a Google search could trivially crack. The motivation was something like, "if you want to take a peek inside, you need to try harder."

Again, this originated in vanilla RPG Maker VX Ace using a DLL. I did port it to my fork partially as an exercise to say I had everything migrated. But that's also where things change. mkxp(-z) is GPL. Part of what gets encrypted is executable code. GPL says "pls provide source for all code thanks". In compliance with this, encryption of Ruby code is officially off the table. As an aside, this also means that you actually can't distribute RGSSAD archives with your mkxp game. People do it, but you're not supposed to.

Even if the license weren't a blocker, it's a pointless effort anyway. Once Ruby code gets loaded, the decrypted plaintext exists freely in memory. Even if you have the bestest most strongerest encryption on the planet, it isn't going to do its job when the asset must exist unencrypted in RAM. Anybody can sift through memory to grab what they want if they so desire. While I am not certain, I feel like the same principle would probably apply to non-code assets.

This is on top of what Splendide-Imaginarius said. All asset encryption can really do is slow down cracking which, once done, no longer serves this purpose.

**Comment by Splendide-Imaginarius** [comment]
Agree with everything @Eblo said, with the slight caveat that last I looked, case law was basically nonexistent on whether the GPL could cross the bindings between C++ and Ruby. Maybe it can (FSF says it can), but I think an argument could be made that copyright law would consider the bindings to be an "interface", not a "derived work", which would mean the GPL (and any copyright license) can't cross that boundary. Anyway, the fact that we don't know 100% whether it's legal is already sufficient for me to want to stay away from that, plus all the other issues Eblo said.
